[2023-07-02T04:51:46.333+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_operator_dag.create_news_table manual__2023-07-02T04:51:45.951679+00:00 [queued]>
[2023-07-02T04:51:46.339+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_operator_dag.create_news_table manual__2023-07-02T04:51:45.951679+00:00 [queued]>
[2023-07-02T04:51:46.339+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-07-02T04:51:46.349+0000] {taskinstance.py:1327} INFO - Executing <Task(PostgresOperator): create_news_table> on 2023-07-02 04:51:45.951679+00:00
[2023-07-02T04:51:46.354+0000] {standard_task_runner.py:57} INFO - Started process 1397 to run task
[2023-07-02T04:51:46.356+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'postgres_operator_dag', 'create_news_table', 'manual__2023-07-02T04:51:45.951679+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/create_tables.py', '--cfg-path', '/tmp/tmprlo35szz']
[2023-07-02T04:51:46.356+0000] {standard_task_runner.py:85} INFO - Job 9: Subtask create_news_table
[2023-07-02T04:51:46.391+0000] {task_command.py:410} INFO - Running <TaskInstance: postgres_operator_dag.create_news_table manual__2023-07-02T04:51:45.951679+00:00 [running]> on host d409bdcb9602
[2023-07-02T04:51:46.458+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='postgres_operator_dag' AIRFLOW_CTX_TASK_ID='create_news_table' AIRFLOW_CTX_EXECUTION_DATE='2023-07-02T04:51:45.951679+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-02T04:51:45.951679+00:00'
[2023-07-02T04:51:46.458+0000] {sql.py:265} INFO - Executing: 
            CREATE TABLE IF NOT EXISTS news (
                "hash" TEXT,
                "title" TEXT,
                "category" TEXT,
                "date" DATE,
                "body" TEXT,
                "raw_content" TEXT,
                "source_entity" TEXT,
                "link" TEXT,

                "generated_summary" TEXT,
                "negative_score" NUMERIC,
                "importance_score" NUMERIC,


                PRIMERY KEY (hash)
            );
[2023-07-02T04:51:46.466+0000] {base.py:73} INFO - Using connection ID 'conn_postgres_id' for task execution.
[2023-07-02T04:51:46.522+0000] {base.py:73} INFO - Using connection ID 'conn_postgres_id' for task execution.
[2023-07-02T04:51:46.525+0000] {sql.py:375} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS news (
                "hash" TEXT,
                "title" TEXT,
                "category" TEXT,
                "date" DATE,
                "body" TEXT,
                "raw_content" TEXT,
                "source_entity" TEXT,
                "link" TEXT,

                "generated_summary" TEXT,
                "negative_score" NUMERIC,
                "importance_score" NUMERIC,


                PRIMERY KEY (hash)
            );, parameters: None
[2023-07-02T04:51:46.526+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 277, in execute
    **extra_kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 349, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 380, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedObject: type "key" does not exist
LINE 17:                 PRIMERY KEY (hash)
                                 ^

[2023-07-02T04:51:46.532+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=postgres_operator_dag, task_id=create_news_table, execution_date=20230702T045145, start_date=20230702T045146, end_date=20230702T045146
[2023-07-02T04:51:46.541+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 9 for task create_news_table (type "key" does not exist
LINE 17:                 PRIMERY KEY (hash)
                                 ^
; 1397)
[2023-07-02T04:51:46.568+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-02T04:51:46.583+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
