[2023-07-07T19:02:37.083+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_scrap_biobio_v7.scrap_data scheduled__2023-07-06T00:00:00+00:00 [queued]>
[2023-07-07T19:02:37.090+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_scrap_biobio_v7.scrap_data scheduled__2023-07-06T00:00:00+00:00 [queued]>
[2023-07-07T19:02:37.090+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-07-07T19:02:37.099+0000] {taskinstance.py:1327} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): scrap_data> on 2023-07-06 00:00:00+00:00
[2023-07-07T19:02:37.103+0000] {standard_task_runner.py:57} INFO - Started process 2187 to run task
[2023-07-07T19:02:37.106+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_scrap_biobio_v7', 'scrap_data', 'scheduled__2023-07-06T00:00:00+00:00', '--job-id', '89', '--raw', '--subdir', 'DAGS_FOLDER/dag_scrap_biobio.py', '--cfg-path', '/tmp/tmp4gxt8eee']
[2023-07-07T19:02:37.106+0000] {standard_task_runner.py:85} INFO - Job 89: Subtask scrap_data
[2023-07-07T19:02:37.137+0000] {task_command.py:410} INFO - Running <TaskInstance: dag_scrap_biobio_v7.scrap_data scheduled__2023-07-06T00:00:00+00:00 [running]> on host d409bdcb9602
[2023-07-07T19:02:37.195+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_scrap_biobio_v7' AIRFLOW_CTX_TASK_ID='scrap_data' AIRFLOW_CTX_EXECUTION_DATE='2023-07-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-07-06T00:00:00+00:00'
[2023-07-07T19:02:37.195+0000] {process_utils.py:181} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venvmzqb0a15
[2023-07-07T19:02:37.202+0000] {process_utils.py:185} INFO - Output:
[2023-07-07T19:02:37.956+0000] {process_utils.py:189} INFO - created virtual environment CPython3.7.17.final.0-64 in 157ms
[2023-07-07T19:02:37.956+0000] {process_utils.py:189} INFO -   creator CPython3Posix(dest=/tmp/venvmzqb0a15, clear=False, no_vcs_ignore=False, global=False)
[2023-07-07T19:02:37.956+0000] {process_utils.py:189} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2023-07-07T19:02:37.956+0000] {process_utils.py:189} INFO -     added seed packages: pip==23.1.2, setuptools==67.8.0, wheel==0.40.0
[2023-07-07T19:02:37.956+0000] {process_utils.py:189} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2023-07-07T19:02:37.988+0000] {process_utils.py:181} INFO - Executing cmd: /tmp/venvmzqb0a15/bin/pip install -r /tmp/venvmzqb0a15/requirements.txt
[2023-07-07T19:02:37.995+0000] {process_utils.py:185} INFO - Output:
[2023-07-07T19:02:39.093+0000] {process_utils.py:189} INFO - Collecting selenium (from -r /tmp/venvmzqb0a15/requirements.txt (line 1))
[2023-07-07T19:02:39.105+0000] {process_utils.py:189} INFO -   Using cached selenium-4.10.0-py3-none-any.whl (6.7 MB)
[2023-07-07T19:02:39.285+0000] {process_utils.py:189} INFO - ERROR: Could not find a version that satisfies the requirement hashlib (from versions: 20081119)
[2023-07-07T19:02:39.286+0000] {process_utils.py:189} INFO - ERROR: No matching distribution found for hashlib
[2023-07-07T19:02:39.503+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 220, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 374, in execute
    return super().execute(context=serializable_context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 575, in execute_callable
    pip_install_options=self.pip_install_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/python_virtualenv.py", line 99, in prepare_virtualenv
    execute_in_subprocess(pip_cmd)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/process_utils.py", line 170, in execute_in_subprocess
    execute_in_subprocess_with_kwargs(cmd, cwd=cwd)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/process_utils.py", line 193, in execute_in_subprocess_with_kwargs
    raise subprocess.CalledProcessError(exit_code, cmd)
subprocess.CalledProcessError: Command '['/tmp/venvmzqb0a15/bin/pip', 'install', '-r', '/tmp/venvmzqb0a15/requirements.txt']' returned non-zero exit status 1.
[2023-07-07T19:02:39.509+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=dag_scrap_biobio_v7, task_id=scrap_data, execution_date=20230706T000000, start_date=20230707T190237, end_date=20230707T190239
[2023-07-07T19:02:39.519+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 89 for task scrap_data (Command '['/tmp/venvmzqb0a15/bin/pip', 'install', '-r', '/tmp/venvmzqb0a15/requirements.txt']' returned non-zero exit status 1.; 2187)
[2023-07-07T19:02:39.529+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-07T19:02:39.541+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
