[2023-07-10T15:02:32.181+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_scrap_biobio_v13.scrap_data manual__2023-07-10T15:02:29.998826+00:00 [queued]>
[2023-07-10T15:02:32.187+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_scrap_biobio_v13.scrap_data manual__2023-07-10T15:02:29.998826+00:00 [queued]>
[2023-07-10T15:02:32.187+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-07-10T15:02:32.197+0000] {taskinstance.py:1327} INFO - Executing <Task(_PythonDecoratedOperator): scrap_data> on 2023-07-10 15:02:29.998826+00:00
[2023-07-10T15:02:32.201+0000] {standard_task_runner.py:57} INFO - Started process 1481 to run task
[2023-07-10T15:02:32.202+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_scrap_biobio_v13', 'scrap_data', 'manual__2023-07-10T15:02:29.998826+00:00', '--job-id', '169', '--raw', '--subdir', 'DAGS_FOLDER/dag_scrap_biobio.py', '--cfg-path', '/tmp/tmp5wzlslyh']
[2023-07-10T15:02:32.203+0000] {standard_task_runner.py:85} INFO - Job 169: Subtask scrap_data
[2023-07-10T15:02:32.233+0000] {task_command.py:410} INFO - Running <TaskInstance: dag_scrap_biobio_v13.scrap_data manual__2023-07-10T15:02:29.998826+00:00 [running]> on host 3371e7602d27
[2023-07-10T15:02:32.293+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_scrap_biobio_v13' AIRFLOW_CTX_TASK_ID='scrap_data' AIRFLOW_CTX_EXECUTION_DATE='2023-07-10T15:02:29.998826+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-10T15:02:29.998826+00:00'
[2023-07-10T15:02:32.728+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 220, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_scrap_biobio.py", line 111, in scrapData
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2023-07-10T15:02:32.734+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=dag_scrap_biobio_v13, task_id=scrap_data, execution_date=20230710T150229, start_date=20230710T150232, end_date=20230710T150232
[2023-07-10T15:02:32.748+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 169 for task scrap_data (No module named 'pyspark'; 1481)
[2023-07-10T15:02:32.777+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-10T15:02:32.790+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
