[2023-07-10T16:43:38.509+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_scrap_biobio_v13.scrap_data manual__2023-07-10T16:43:36.643853+00:00 [queued]>
[2023-07-10T16:43:38.516+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_scrap_biobio_v13.scrap_data manual__2023-07-10T16:43:36.643853+00:00 [queued]>
[2023-07-10T16:43:38.516+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-07-10T16:43:38.525+0000] {taskinstance.py:1327} INFO - Executing <Task(_PythonExternalDecoratedOperator): scrap_data> on 2023-07-10 16:43:36.643853+00:00
[2023-07-10T16:43:38.529+0000] {standard_task_runner.py:57} INFO - Started process 3239 to run task
[2023-07-10T16:43:38.531+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_scrap_biobio_v13', 'scrap_data', 'manual__2023-07-10T16:43:36.643853+00:00', '--job-id', '171', '--raw', '--subdir', 'DAGS_FOLDER/dag_scrap_biobio.py', '--cfg-path', '/tmp/tmpgz6dnnw0']
[2023-07-10T16:43:38.531+0000] {standard_task_runner.py:85} INFO - Job 171: Subtask scrap_data
[2023-07-10T16:43:38.561+0000] {task_command.py:410} INFO - Running <TaskInstance: dag_scrap_biobio_v13.scrap_data manual__2023-07-10T16:43:36.643853+00:00 [running]> on host 3371e7602d27
[2023-07-10T16:43:38.619+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_scrap_biobio_v13' AIRFLOW_CTX_TASK_ID='scrap_data' AIRFLOW_CTX_EXECUTION_DATE='2023-07-10T16:43:36.643853+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-10T16:43:36.643853+00:00'
[2023-07-10T16:43:39.227+0000] {process_utils.py:181} INFO - Executing cmd: /usr/local/bin/python3.7 /tmp/tmd1tw2m9ns/script.py /tmp/tmd1tw2m9ns/script.in /tmp/tmd1tw2m9ns/script.out /tmp/tmd1tw2m9ns/string_args.txt
[2023-07-10T16:43:39.235+0000] {process_utils.py:185} INFO - Output:
[2023-07-10T16:43:40.217+0000] {process_utils.py:189} INFO - Traceback (most recent call last):
[2023-07-10T16:43:40.217+0000] {process_utils.py:189} INFO -   File "/tmp/tmd1tw2m9ns/script.py", line 160, in <module>
[2023-07-10T16:43:40.217+0000] {process_utils.py:189} INFO -     res = scrapData(*arg_dict["args"], **arg_dict["kwargs"])
[2023-07-10T16:43:40.217+0000] {process_utils.py:189} INFO -   File "/tmp/tmd1tw2m9ns/script.py", line 37, in scrapData
[2023-07-10T16:43:40.218+0000] {process_utils.py:189} INFO -     from pyspark.sql import SparkSession
[2023-07-10T16:43:40.218+0000] {process_utils.py:189} INFO - ModuleNotFoundError: No module named 'pyspark'
[2023-07-10T16:43:40.278+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 220, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 374, in execute
    return super().execute(context=serializable_context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 696, in execute_callable
    return self._execute_python_callable_in_subprocess(python_path, tmp_path)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 434, in _execute_python_callable_in_subprocess
    os.fspath(string_args_path),
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/process_utils.py", line 170, in execute_in_subprocess
    execute_in_subprocess_with_kwargs(cmd, cwd=cwd)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/process_utils.py", line 193, in execute_in_subprocess_with_kwargs
    raise subprocess.CalledProcessError(exit_code, cmd)
subprocess.CalledProcessError: Command '['/usr/local/bin/python3.7', '/tmp/tmd1tw2m9ns/script.py', '/tmp/tmd1tw2m9ns/script.in', '/tmp/tmd1tw2m9ns/script.out', '/tmp/tmd1tw2m9ns/string_args.txt']' returned non-zero exit status 1.
[2023-07-10T16:43:40.288+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=dag_scrap_biobio_v13, task_id=scrap_data, execution_date=20230710T164336, start_date=20230710T164338, end_date=20230710T164340
[2023-07-10T16:43:40.297+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 171 for task scrap_data (Command '['/usr/local/bin/python3.7', '/tmp/tmd1tw2m9ns/script.py', '/tmp/tmd1tw2m9ns/script.in', '/tmp/tmd1tw2m9ns/script.out', '/tmp/tmd1tw2m9ns/string_args.txt']' returned non-zero exit status 1.; 3239)
[2023-07-10T16:43:40.312+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-10T16:43:40.331+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
